thestk/rtaudio

RtAudio.cpp
When the stream is closed on Mac, the property listener is not removed.
=> Fix closeStream on Mac OS X

tests/duplex.cpp
This change was necessary to prevent BAD ACCESS when compiling on 64 bit OSX
=> duplex test: 64 bit compatibility

RtAudio.cpp
Hi.
```
$ clang -framework CoreAudio -framework CoreFoundation -D__MACOSX_CORE__ -lc++ RtAudio.cpp main.cpp
```
just after clone from github master, above command fails with compile errors.
```
RtAudio.cpp:1477:1: error: function definition is not allowed here
{
^
RtAudio.cpp:1518:1: error: function definition is not allowed here
{
^
RtAudio.cpp:1561:1: error: function definition is not allowed here
{
^
RtAudio.cpp:1581:1: error: function definition is not allowed here
{
^
...
```
these are caused by this duplecated line.
so, this PR deletes second line.
```
if ( stream_.mode == OUTPUT || stream_.mode == DUPLEX ) {
if ( stream_.mode == OUTPUT || stream_.mode == DUPLEX ) {
```
Regards.
=> fix compile errors with -D__MACOSX_CORE__

RtAudio.cpp
Some situations like removing a device, the function GetCurrentPosition fails and, when return, does not unlock the mutex.
=> Release lock if GetCurrentPosition from DS failed

configure.ac
I noticed an inconsistency between configure.ac and RtAudio.h in the version number.  This fixes it and adds a check for this to configure.ac.
=> Fix version and add version check

tests/duplex.cpp
This reverts commit f639653f5ecf98d3b093049435df5631d8eb0f44.
This change breaks the build with g++ 5.2.1, it complains:
duplex.cpp:58:3: error: ‘uint32_t’ was not declared in this scope
uint32_t *bytes = (uint32_t *) data;
It requires `#include <cstdint>`, which would require c++11 support, or `#include <stdint.h>`, which is known to be problematic on Windows.
Moreover, changing "unsigned int" to "uint32_t" shouldn't change anything on either 32- or 64-bit systems, since they are the same.  I tested it on an iMac running 10.8.5 and I did not get a Bus Error.  Can anyone verify that duplex crashes for them on a Mac without this change?  If so we should be able to find a solution that doesn't involve stdint.h, preferably.
=> Revert "duplex test: 64 bit compatibility"

configure.ac
CXXFLAGS should be set before AC_PROG_CXX.  This patch uses a syntax allowing it to be overridden during "env CXXFLAGS=... ./configure", "./configure CXXFLAGS=..." or during "make CXXFLAGS=..."
Keeps previous behaviour of -O3 for normal builds, -g -O0 for debug builds, and keeps the define `__RTAUDIO_DEBUG__`, however this is done using AC_DEFINE.
(Based on a [stackoverflow answer](http://stackoverflow.com/questions/3116645/default-compiler-flags-with-autotools))
=> Fix handling of CXXFLAGS in configure.ac.

RtAudio.cpp, RtAudio.h
Add C++0x compatible exception semantics. This is probably not yet compatible accross compilers - ~~and not backwards compatibile as well~~ (**EDIT:** should be backwards compatible). Could someone review and check this, please? Would be nice to see this become cross-compatible with the "most common" compilers (vs/nmake, clang, gcc).
**CHECKS (Help wanted!)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thestk/rtaudio/67)
=> refactor: C++0x compatible exception semantics

RtAudio.cpp
Windows testers needed please.
See if this helps with #78.
Is it necessary?  Does it break anything?
=> Add mmsystem.h and mmreg.h for dsound.

RtAudio.cpp, RtAudio.h
I propose a patch to implement what the title says.
RtAudio will connect the Jack ports as the program initializes, which is not always the desired behavior, and it lacks a programmatic way to disable this.
On the typical Linux softsynth, it is expected to begin unconnected and let the user manage connections externally, either manually or using the patch bay.
The patch does not modify existing behavior, instead it introduces a stream flag to realise my desired behavior. I have tried the functionality on a softsynth I am currently developing.
=> a JACK-specific flag to disable automatic connection of ports

contrib/go/rtaudio/rtaudio.go
- Use static build flag for windows to work around mingw issues (MinGW on windows otherwise has duplicate symbols because it tries both static and dynamic libraries at the same time)
- Use array sizes adjusted for 32-bit systems (otherwise on 32-bit systems there would be build errors because array size can theoretically exceed 32-bit address space).
=> go binding fixes

RtAudio.cpp
Rounding needs to be done like in this line: https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L3886
I had a heap corruption when the Windows 10 system sound is set to 48kHz 16Bit and I setup RtAudio with 44.1kHz 16Bit which needs to be converted in [convertBufferWasapi]. The cast done in this line: https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L4981 truncates and afterwards is missing one sample (which leads to heap corruption when free'ing the buffer on shut down). Therefore [roundf] is needed.
Please also check the other code paths like in [stream_.mode == INPUT]. I just corrected the one I am using. I am also not quite sure if this is the best way of fixing it. But you know the code best.
=> Round floats by using roundf in order to round correctly.

RtAudio.cpp
Usually on Linux when PulseAudio is present ALSA would give errors when trying to open the device (due to it being already open by PulseAudio), so this gives more priority to PulseAudio.
=> Give more priority to PulseAudio api

CMakeLists.txt
My platform is windows, my compiler mingw-w64.
I got this error on cmake <code>install Library TARGETS given no DESTINATION!</code> and after googling I arrived to this, which means reverting part of PR  #126 @claudiocabral
=> avoid cmake error: "install Library TARGETS given no DESTINATION!"

.travis.yml, configure.ac
This is an idea for reorganizing the way APIs are detected at configure time.
Instead of wrapping up OS detection with expected APIs, and giving errors for unknown OS, first the `with` options are considered, then *only if there are none specified*, the OS is detected and some defaults are suggested.  Then, any APIs on that list are tested regarding found libraries.  APIs specified by `with` options are considered 'required' (error generated if not found), otherwise they are optional (not-found APIs are ignored).
This allows unknown OSs to still specify an API using `with` options, and makes it easier to manage which OSs are associated with which APIs, and also avoids repeating detection code for multiple OSs that support a single API.
This addresses #107, #110, #116.
=> autoconf: separate OS defaults and audio API testing

tests/audioprobe.cpp
Add device id to `audioprobe` output, useful when used in conjunction with a tool that requires the input of the `rtaudio` device id such as `jackTrip` PR: https://github.com/jcacerec/jacktrip/pull/36
=> Add device id to audioprobe output

CMakeLists.txt, RtAudio.cpp, RtAudio.h, configure.ac, contrib/go/rtaudio/rtaudio.go, doc/doxygen/compiling.txt
As WASAPI itself does not provide support for sample rates other than the current system default, I've introduced the Microsoft MFT (Media Foundation Transform) library into RtApiWasapi in order to allow users to specify the sample rate they wish to use.
=> Fix Issue #69 - Allow non-default sample rates in WASAPI

RtAudio.cpp
fixes #138 
Not raising a fatal error when WASAPI is not instantiable.
This allows Windows XP to fall back to DirectSound.
=> make WASAPI instantiation errors non-fatal for older Windows

RtAudio.cpp, RtAudio.h, doc/doxygen/probe.txt, install.txt
This PR fixes the spelling of "e.g.", changes "ex." to "e.g.", and fixes some missing punctuation found while making those edits.
=> Fix spelling of "e.g."

CMakeLists.txt
As is, the CMakeLists.txt configuration file references the project source directory, making this repository impossible to use as-is as a git submodule in other projects. These changes allow for configuration of rtaudio as a submodule from anywhere. Tested locally with a very simple example by compiling against the static lib, works fine for me.
=> CMake - Use current directory

RtAudio.cpp
In the case where the default audio device is loaded in probeDeviceOpen, the ALSA CTL handle was not being closed. In my case (running Debian 9), every call to snd_ctl_open created a PulseAudio thread in the back-end which only exits upon calling snd_ctl_close. So, every time a stream was opened, a dangling thread would be created. This edit seems to have fixed the issue.
=> Fix ALSA CTL handle not being closed in the default case

rtaudio_c.cpp
It was not a good idea to cast enum array from C++ to C. Solved it with the simplest idea that came to mind. Maybe there are better ways, but this one worked, so I left it.
=> fix go build due to enum casts

rtaudio_c.cpp
Related to #163 but does not break the build anymore.
=> Fix Go build due to enum casting

RtAudio.cpp
This change allows WASAPI users to capture "loopback" streams from render devices.
=> Add loopback support to WASAPI

RtAudio.h
There is a function that appears in most of the derived API classes, called `getStreamLatency`. Since it is implemented in the base class, and it is non-virtual, I take it that it was not meant to show up in the derived classes. This PR removes the prototype definition from the derived API classes. I tested the build with ALSA, JACK, and Pulse.
=> Removed Unused Function

CMakeLists.txt
Avoids this error
C:\luaGL\gitsources\luaRtAudio\rtaudio\RtAudio.cpp:3758:43: fatal error: functiondiscoverykeys_devpkey.h: No such file or directory
#include <functiondiscoverykeys_devpkey.h>
=> CMakeLists: avoid include error: 

rtaudio_c.cpp, rtaudio_c.h
In the c implementation: The const unsigned int rtaudio_num_compiled_apis is not exported in ffi interfaces of modules, so it is here returned by a function.
=> rtaudio_c: add rtaudio_num_compiled_api()

RtAudio.cpp
Forgive me. The previous committed "fix" for #170 was incorrect. This is the proper fix.
=> #170 : Insert missing render memcpy when !doConvertBuffer in WASAPI

Makefile.am, RtAudio.cpp, RtAudio.h, configure.ac
Fixes #144.
Added to each one because... shouldn't Windows apis use QueryPerformanceCounter instead of gettimeofday?
In any case perhaps with C++11 this can be replaced with std::chrono.
=> Update lastTickTimestamp in startStream.

CMakeLists.txt
I am writing a portfile for [vcpkg](https://github.com/Microsoft/vcpkg) to be able to use RtAudio as a dependency.
As RtAudio already uses CMake, I thought I could try to update the build system to better use more modern CMake conventions and practices, which should allow a smoother integration with other projects.
Here is an overview of the changes:
- The project now only builds either shared _or_ static libraries
- The exported targets include the dependency on pthreads when it is built with it
- The Debug suffix for the Windows library has been removed, CMake automatically handles the build type with the `--config` flag
=> Update CMake build system

RtAudio.cpp
When compiling with WASAPI on my windows machine, the build fails since the type of a variable captureFlags (unsigned long) does not match the windows DWORD type (unsigned int) in a function call. Changing the captureFlags type to DWORD seems to be the most reliable fix for this issue since it ensures that captureFlags is processor independent.
=> Change type of captureFlags to DWORD

RtAudio.cpp
This is a basic proof of concept to get the really preferred sample rate from pulseaudio async api.
=> PulseAudio: get preferredSampleRate

CMakeLists.txt
When using the CMake build, I only get this one header installed:
- /usr/include/RtAudio.h
However when using the autotools build, I get two headers in a subfolder:
- /usr/include/rtaudio/RtAudio.h
- /usr/include/rtaudio/rtaudio_c.h
This PR changes the CMake build to match the autotools behavior. This could be a problem though if CMake users have come to depend on the old behavior of not installing to a subfolder, so maybe this is not the best solution?
=> Adjust CMake public header installs to match autotools

RtAudio.cpp
This changes the int<->float conversion from `int(x*(2^n-0.5)-0.5)` to `min(round(x*2^n), 2^n-1)`.
The new method is symmetric, invertible (meaning `f(f^-1(x)) = x` except for clipping), and aligns with the granularity of floats better (e.g. `0.25 / 2^n` is a nice round number).
Caveats:
It is slower (10 instructions with `-O3 -ffast-math` vs. 3 instructions with the current method), but I feel it is more "correct" and straightforward.
It uses `std::lround` which I believe is C++11, but old C++98 compilers might accept it anyway since it's an ancient C function.
Accept or reject this PR, I don't care either way.
According to this article, this method is used by CoreAudio and ALSA, and possibly others.
http://blog.bjornroche.com/2009/12/int-float-int-its-jungle-out-there.html
Fixes …
=> Change float<->int conversion to x*2^n

RtAudio.cpp
AlsaHandle::handles members are not initialised
=> Add missing initialisation for AlsaHandle::handles

CMakeLists.txt, RtAudio.h, configure.ac, m4/ax_cxx_compile_stdcxx.m4
This adds the "override" keyword which C++11 compilers warn against forgetting, causing problems with `-Werror`.
=> Add override keyword

RtAudio.cpp
Old behavior is retained if `StreamOptions*` is null or `numberOfBuffers` is 0.
I pass in a null `pa_buffer_attr*` to maintain current behavior. If you instead pass in a non-null pointer where all parameters are -1, then you get around two seconds of latency, which is unacceptable.
Fixes #262.
=> Make PulseAudio backend use correct numberOfBuffers

RtAudio.cpp
I'm dumb and used `long` instead of `long long` in a PR several months ago. On Linux/Mac this works fine, but on MSVC and Mingw, `sizeof(long) == 4` so `lround(1.0 * 2147483648.f)` was overflowing to 0x80000000.
Fixed by using `llround()` and `long long` literals.
=> Fix convertBuffer() when converting the value "1.0" from float32 or float64 to SINT32

RtAudio.h
This small change makes it nicer to initialize an object, and avoids possible runtime reassignment in the case of non-trivial types. So instead of:
```cpp
RtAudio::StreamParameters output_params;
output_params.nChannels = 1;
output_params.firstChannel = 0;
output_params.deviceId = dac.getDefaultOutputDevice();
```
You can just write:
```cpp
RtAudio::StreamParameters output_params {1, 0, dac.getDefaultOutputDevice()};
```
Or even better in C++20
```cpp
RtAudio::StreamParameters output_params {
.nChannels = 1, 
.firstChannel = 0, 
.deviceId = dac.getDefaultOutputDevice()
};
```
=> Default initialized members instead of user-defined default constructors

RtAudio.cpp
Previously, RtAudio casted a char-based string literal to a `TCHAR const*`, and passed it into `LoadLibrary` (a `#define`). With UNICODE defined, `TCHAR` is `wchar_t` and `LoadLibrary` maps to `LoadLibraryW` (which expects UTF-16 input). Windows interprets the string literal as UTF-16 and tries loading `噁呒搮汬.DLL` instead. Even worse, this performs an out-of-bounds read because when loading UTF-16 null-terminated strings, Windows looks for two consecutive null bytes. If the string literal's null terminator isn't followed by a second null byte in the program's memory layout, Windows might read even more gibberish and try to interpret it as UTF-16. (This is *probably* harmless but still bad.)
This PR changes it to unconditionally call `LoadLibraryW` and pass in a UTF-16 string literal. My …
=> Fix WASAPI backend loading AVRT.dll with UNICODE defined

include/asiolist.cpp
That seems to cause MinGW build failures in debug builds, see microsoft/vcpkg#17617
=> asiolist.cpp: remove unused variable

meson.build, meson_options.txt
When building JackTrip I've used RtAudio as a cmake subproject in meson. I had to handle a lot of dependency things that should actually be handled by the subproject. So I decided to write meson build files for RtAudio. This simplifies a lot for me and I got rid of some linking errors on Windows. Additionally there would be the possibility to add RtAudio to the [WrapDB](https://wrapdb.mesonbuild.com/).
[This](https://github.com/jacktrip/jacktrip/pull/301) is the corresponding change in JackTrip.
=> Add Meson build

RtAudio.cpp, RtAudio.h
On all Linux PulseAudio systems, calling `RtAudio::getDefaultOutputDevice()` with the PulseAudio backend returns device 0. This is because `RtApiPulse::getDefaultOutputDevice()` is not defined and calling it invokes the base-class method `RtApi::getDefaultOutputDevice()`, which is a placeholder which always returns 0. But on computers where the default input/output devices don't share the same name, this is an input-only device which cannot be used as output, meaning the returned default output device cannot be used to open a stream.  (getDefaultInputDevice() may also be wrong in rare cases. Details on why these happen are at #295.)
The idea I came up with was to loop over `RtApi::getDeviceInfo()` and return the (hopefully exactly 1) device labeled as a default. To my surprise, this code …
=> Fix PulseAudio getDefaultOutputDevice() and getDefaultInputDevice()

meson.build
This adds a summary about which audio backends get compiled. It gets also shown in the summary of superprojects (like JackTrip). It looks like this but with color:
```
RtAudio undefined
Audio Backends
ALSA: YES
OSS: NO
JACK: YES
PulseAudio: YES
CoreAudio: NO
DirectAudio: NO
WASAPI: NO
ASIO: NO
```
Other changes should lead to a build that is more similar to the cmake one. The last things that are missing are setting the project version and pkgconfig as well as cmake file generation.
=> Meson improvements

meson.build
This change lets Meson generate a pkgconfig file that looks like this (edit: removed defines):
```
prefix=/usr/local
libdir=${prefix}/lib64
includedir=${prefix}/include
Name: rtaudio
Description: RtAudio - a set of C++ classes that provide a common API for realtime audio input/output
Version: 5.1.0
Requires.private: alsa, jack, libpulse-simple
Libs: -L${libdir} -lrtaudio
Libs.private: -pthread
Cflags: -I${includedir}/rtaudio
```
It would be quite interesting if Meson adds apple frameworks to Libs.private. Then #302 would be fixed with that (at least for Meson). 
There are two things different to the rtaudio.pc.in file.
1. All dependencies are private because RtAudio doesn't expose any types or API from them.
2. The libdir for Fedora gets correctly set to lib64.
~~RTAUDIO_EXPORT seems to …
=> Let Meson generate pkgconfig file

RtAudio.cpp
For a long time, RtAudio has called `pa_context_get_server_info` which schedules `rt_pa_server_callback` which calls `rt_pa_mainloop_api_quit(0)`. The calls to `pa_context_get_sink_info_list(context, rt_pa_sink_info_cb, NULL)` and `pa_context_get_source_info_list(context, rt_pa_source_info_cb, NULL)` was added later on in c0d33839f522710e5a616a0b5e43d42d95096c7f, but the author forgot to move `rt_pa_mainloop_api_quit(0)` to the last function called (`rt_pa_source_info_cb` with `eol=1`). However, the code still works most of the time by accident: if the PulseAudio server establishes a `pa_srbchannel` connection to the RtAudio app and sends messages fast enough, the client's `pa_mainloop_run` will continue popping sink/source messages from the channel and running `rt_pa_sink_info_cb` and …
=> Fix bug where PulseAudio devices are randomly not detected

CMakeLists.txt
Fix #283
I just went for fixing this and I realized there was an issue already opened reporting the same problem.
I tested on macOS and it works. @autoantwort can you give it a try?
EDIT:
Just for completeness, the problem reported in the issue is not exactly the same but it is somehow correlated.
Indeed, I would suggest to use the project like this
```cmake
find_package(RtAudio)
add_exectuable(... PRIVATE RtAudio::rtaudio)
```
specifying the install root path in `RtAudio_ROOT` if needed (as env variable or cmake cache variable).
=> Fix header problem with CMake package configuration file

RtAudio.cpp
Previously, when calling `RtApi::getDefaultInputDevice()` or `RtApi::getDefaultOutputDevice()`, every iteration of the for loop until the default device was found (up to O(n)) would call `getDeviceCount`. On PulseAudio, this would call `RtApiPulse::collectDeviceInfo` and rescan the list of devices (O(n)), resulting in up to O(n^2) runtime with the number of devices. Additionally it could result in tearing where the device count changes midway through the loop.
This changes the code to cache the device count upfront, which shouldn't have any negative effects hopefully.
Tested on PulseAudio and ALSA.
Discovered at https://github.com/thestk/rtaudio/pull/296#issuecomment-890134199.
=> Don't repeatedly compute device count when locating default device

RtAudio.cpp
This doesn't change behavior in my testing, since I haven't seen `rt_pa_server_callback` get called with a null `const pa_server_info *info`. But it seems the code tries to handle that case, but gets it wrong. rt_pa_mainloop_api_quit doesn't return from the function, it only stops the event loop from running more callbacks, so it's not safe to continue executing the function and dereference `info`.
I'm actually not sure if it's a good idea to overwrite `rt_pa_info` with some value if `info` is null. And I don't know if the value of `rt_pa_mainloop_api_quit(1)` actually gets checked anywhere, or if the error gets lost in transit.
=> Fix null pointer dereference in rt_pa_server_callback

tests/audioprobe.cpp
Allows to select the API by index (into the displayed list of compiled APIs) or by short name.
If no argument, list all devices of all compiled APIs.
=> audioprobe: list devices for all APIs

RtAudio.cpp
As per https://jackaudio.org/api/group__PortSearching.html jack_get_ports accepts a regular expression for the port name. Kind of weird but whatever. Unfortunately current usage of the jack_get_ports API causes issues when port names have certain characters in them - and this is quite common to encounter on newer Linux distributions like Fedora 35 and RHEL 8 where PipeWire is the default and jack audio API is default available through their PipeWire config.
=> Fix Usage of jack_get_ports API

RtAudio.cpp
I encountered a rare case among my beta testers where Windows 10 would return 10 render devices when only 9 were publicly listed in Windows Sound Playback panel. That 10th device seemed to be a ghost device with no name and no user visibility.
As a result, when RtAudio was querying the 10th device name, devicePropStore->GetValue( PKEY_Device_FriendlyName, &deviceNameProp ) returned no error, but deviceNameProp.pwszVal was set to nullptr, which then leaded to a crash.
Making sure that deviceNameProp.pwszVal is not null avoid that crash.
I also added a similar check for defaultDeviceNameProp.pwszVal.
For reference all the details about that crash are in that private beta forum: https://forums.steinberg.net/t/spectralayers-9-0-0-283-not-launching-windows-10/784659/24
=> handle a rare case where wasapi would not return the device name

README.md, install.txt
Rtaudio is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for rtaudio and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build rtaudio, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/rtaudio/portfile.cmake). We try to keep the library maintained as close as possible to the original library.
=> Add vcpkg installation instructions

RtAudio.cpp
Hi,
I heard artifacts on some songs while using RtAudio to record my PC's audio.
When recording from float formats, it seems that some values can fall out of the expected range.
Adding std::max alongside the existing std::min calls work around the issue.
Let me know if that's not correct.
I'm using macOS 12.6, I don't know if it's specific to CoreAudio.
Repro:
- Install a virtual audio device to record the Mac's audio via `brew install blackhole-2ch`
- Set BlackHole as the default input device
- Run `./tests/record 2 48000 10`
- Play [this song](https://pixabay.com/music/upbeat-bounce-114024/) on Firefox or Safari
- Import and play `record.raw` in audacity (2ch, 48kHz, 16-bit)
- The artifacts can be clearly heard after the 5 seconds
Using soundflower instead of BlackHole lead to the same …
=> clamp values when converting from floats

RtAudio.cpp
Hi, thanks for making this project. We found a rare random crash on macOS (less then 1 in 1000) triggered by the following use of RtAudio. It finds the target audio device and quickly open and close the capture. This helps us works around a macOS 12 bug where the system thinks the mic is in use but in fact not.
```c++
void open_close_input(const std::string& device_name) {
RtAudio adc;
for (size_t id = 0; id < adc.getDeviceCount(); ++id) {
auto device = adc.getDeviceInfo(id);
if (device.name.find(device_name) != std::string::npos) {
RtAudio::StreamParameters parameters;
parameters.deviceId = id;
parameters.nChannels = device.inputChannels;
parameters.firstChannel = 0;
unsigned int buffer_frames = 256;
try {
std::cout << "openning microphone..." << std::endl;
adc.openStream(NULL, …
```
=> workaround: check if callback is null before use on macos

RtAudio.cpp
The use of a std::string as an output buffer when using WideCharToMultiByte leads to a subtle problem. The string buffer length is defined as "length-1". If length == 1, then the expression &s[0] leads to an out of bound assert when debugging since the length of the string buffer is zero. Furthermore, the value "length" is passed to WideCharToMultiByte indicating that you can write "length" bytes to the string buffer, however, the string buffer is only "length-1" bytes long.
=> Subtle problem with WideCharToMultiByte

RtAudio.cpp
Fixed leaking of IAudioClient3 interface. Leds on USB audio devices kept flashing even after closing the stream and freeing RtApi object.
=> Fixed leaking of WASAPI IAudioClient3 interface

RtAudio.cpp
The problem: when my ASIO device is unplugged (driver still installed), deviceProbe finds no devices which results in an infinite loop when `RtApiAsio :: probeDevices` invokes getDefaultInputDevice() - which re-invokes  RtApiAsio :: probeDevices.  This problem can be reproduced by running the standard audioprobe test.
In this condition `probeDeviceInfo( info ) == false` around line 3406.
I'm not claiming that my fix is the best fix but have verified that it unclogs the logjam.
=> Asio probe infinite-loop fix.

RtAudio.cpp
This fix the case where 2 devices have the same "pretty name" (e.g: 2 mic as USB dongle.)
=> RtApiAlsa: fix device with same "pretty name" not added to device list

rtaudio_c.h
I found out the enums `rtaudio_error` and `rtaudio_api` in `rtaudio_c.h` were not updated to match their counterparts in `RtAudio.h`, so I fixed it.
=> fix enums in rtaudio_c.h

rtaudio_c.cpp, rtaudio_c.h
Some of the types in the C header were either wrong or not not optimal.
Also, in my Rust bindings to RtAudio https://github.com/BillyDM/rtaudio-sys, I currently need to include an automatic bindings generator in the build system, which is inconvenient since it requires the user of the crate to have Clang installed on their system.
This auto bindings generator is needed because of the two enum types `rtaudio_error_t` and `rtaudio_api_t`. If those types were instead integers, then I could remove that binding generator step from my build system. So I went ahead and made that change too.
=> use optimal types in c header

rtaudio_c.cpp, rtaudio_c.h
I noticed another error with the c headers. The `rtaudio_get_device_info` function needs the device ID, not the index.
=> fix rtaudio_get_device_info

CMakeLists.txt
=> Fix linking error to pthreads with MinGW

CMakeLists.txt
The RTAUDIO_BUILD_TESTING variable stops the testing target ejection but still does an include(CTest) which injects the standard CTest macros from enable_testing(). In rtmidi you include(CTest) inside the guard but in rtaudio you do not; as such using the cmake in a non-ctest project ejects multiple targets.
For now you can get around this with BUILD_TESTING globally off but that means you can't activate your own ctests optionally.
So move the include(CTEst) to be in the same spot as it is in rtmidi.
Thanks for great software!
=> Move include(CTest) to inside testing guard

RtAudio.cpp
The flag handle->disconnectListenerAdded[0] is never set to true for input mode streams because the probeOpenStream() code uses handle->disconnectListenerAdded[mode].
This causes RtAudio to never remove device disconnect listeners, which can cause the listener slots to fill up and an "illegal instruction" error code to be returned when you try to add a new one.
=> Remove CoreAudio device disconnect listener when closing input mode streams

RtAudio.cpp
The `kAudioStreamPropertyPhysicalFormat` query returns the number of channels for the device's first audio stream. If any single, subsequent stream is selected to fulfill the user request, it may use a different number of channels. This mismatch can cause a lot of problems.
=> Use correct number of channels for the selected CoreAudio stream

rtaudio_c.cpp
In the C API, the destruction of `struct rtaudio` is missing in the function `rtaudio_destroy(`).
GCC/Clang leak sanitizers detected this.
=> Missing delete of struct rtaudio in rtaudio_destroy() (C api)

RtAudio.cpp
Use COM smart pointer (`ComPtr`) to simplify memory management in WASAPI code.
This reduces chances of calling `Release()` when a COM object has not been allocated.
=> Use COM smart pointers in WASAPI driver

RtAudio.cpp
Fixes #433.
The issue was caused by creating new copies of ComPtr<IAudioClient> inside WasapiHandle instead of using references to the existing instance.
This likely led to improper management of the COM object's reference count, resulting in no audio output.
=> Fix no output on WASAPI (#433)

CMakeLists.txt
This is just to fix a little inconsistency that may put the `RtAudioConfig.cmake` and `RtAudioConfig-version.cmake` in the wrong folders when installing: when using RtAudio as a submodule or with CMake's `FetchContent`.
`CMAKE_CURRENT_BINARY_DIR` is already being used in other places in the same `CMakeLists.txt` file (see from https://github.com/thestk/rtaudio/blob/af3b361aee64a12aad0e7fea2dc2e2bf406a9ec4/CMakeLists.txt#L322 on).
Thanks!
=> allow RtAudio to be installed with FetchContent

RtAudio.cpp
Subj. `&` was missing, so `captureAudioClient` was never properly initialized.
=> Fix wasapi input handling.

RtAudio.cpp
When building RtAudio on Mac with C++17, a deprecation warning is thrown for the `std::wstring_convert` class. This pull request replaces that usage with conversion functions that have not been deprecated.
=> Replaced deprecated string conversion function

RtAudio.cpp, RtAudio.h, configure.ac
This is required (at least on my system (aarch64, gcc 14.1.1)) because
the convertBuffer function is expecting arrays of S24 to increment
at the same rate as arrays of S32; without this change, when a S24*
pointer increments, it increases by 3 instead of 4 on my system,
causing garbled audio output.
Since this very minor change is an interface change, I have bumped
the version number.
=> S24: change storage to 4 chars

RtAudio.cpp, RtAudio.h
This change allows member functions to be used as audio callbacks with std::bind, which can reduce the amount of user data that needs to be passed into the callback as an input.
=> Switched audio callback from function pointer to std::function

RtAudio.h
One could return the string by const ref or by value, but by const value does not make sense.
=> Return string by const ref to save a copy
