thestk/rtaudio

RtAudio.cpp

Added interpolation to WASAPI's sample rate converter

---

RtAudio.cpp

@zserge can you check if this helps with your problem?

Use "using namespace std" for roundf instead of std::roundf.

---

.gitattributes
rtaudio.pc.in

a PR with minor issues we found during preparing the Debian package

Debian fixes

---

Makefile.am
RtAudio.h
configure.ac
rtaudio.pc.in

here's some more fixes to the autotools build-system, along the spirit of the ones just merged into `RtMidi`.

more fixes

---

RtAudio.cpp

Fixes: https://github.com/thestk/rtaudio/issues/180

WASAPI : Fixed #180 and reduced latency

---

CMakeLists.txt
tests/playraw.cpp
tests/playsaw.cpp
tests/record.cpp
tests/teststops.cpp

Fix CMake VS build

---

RtAudio.cpp

WASAPI : Call tickStreamTime() only once per callback

---

RtAudio.cpp

Fix WASAPI channel offset

---

RtAudio.cpp

Add maxOutSampleCount to WasapiResampler::Convert()

---

RtAudio.cpp

Memory Leak using Alsa on Linux ( RtApiAlsa::probeDeviceOpen )

---

RtAudio.h

Thread member of Callback Info structure is not initialised, add missing initialisation

Add missing initialisation for CallbackInfo thread member

---

CMakeLists.txt

Fixes #256.
Is `if(NOT DEFINED` valid syntax that does what I expect it to?

Add CMake option to pick between static/DLL MSVC runtime

---

RtAudio.cpp

Resolves: https://github.com/thestk/rtaudio/issues/248

convertBuffer(): clear duplex device outBuffer if outJump > inJump

---

RtAudio.cpp

See https://github.com/thestk/rtaudio/issues/270.

Fix "default" ALSA device connection issue

---

CMakeLists.txt
RtAudio.cpp
RtAudio.h

A fix for some issues with #308.

Fix check predefined macros

---

.github/workflows/ci.yml

* Make meson enables the correct API.
* Run installation step and list the final directory contents.
* Archive the resulting tarball after running distcheck.

Github actions improvements

---

.github/workflows/ci.yml

Ubuntu CI was updated and g++ is now g++-9

github: install regular g++

---

RtAudio.cpp
RtAudio.h
configure.ac

Needed for PulseAudio and JACK.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
ping @ntonnaett

use pthreads on MinGW and Cygwin

---

tests/duplex.cpp
tests/playraw.cpp
tests/playsaw.cpp
tests/record.cpp

This is necessary at least for mingw-w64

cstdint in test to allow int16_t

---

rtaudio_c.cpp

I dont see this proxy callback necessary. In fact it works perfectly without it. I am missing something?

proxy callback delete

---

include/asiolist.cpp
include/asiolist.h

see [Issue #436](https://github.com/thestk/rtaudio/issues/436)

fixed unbalanced CoInitialize/CoUninitialize call
